definitions:
  docs.ErrorResponse:
    properties:
      error:
        example: failed to bind json
        type: string
    type: object
  docs.MessageResponse:
    properties:
      id:
        example: 1
        type: integer
      message:
        example: created
        type: string
    type: object
  docs.SubscriptionExample:
    properties:
      price:
        example: 999
        type: integer
      service_name:
        example: Netflix
        type: string
      start_date:
        example: 07-2025
        type: string
      user_id:
        example: 11111111-1111-1111-1111-111111111111
        type: string
    type: object
  docs.SumResponse:
    properties:
      sum_price:
        example: 2997
        type: integer
    type: object
  docs.UpdateSubscriptionExample:
    properties:
      price:
        example: 100
        type: integer
      service_name:
        example: Yandex
        type: string
    type: object
  gorm.DeletedAt:
    properties:
      time:
        type: string
      valid:
        description: Valid is true if Time is not NULL
        type: boolean
    type: object
  subscription-aggregator_internal_model.Subscription:
    properties:
      createdAt:
        type: string
      deletedAt:
        $ref: '#/definitions/gorm.DeletedAt'
      id:
        type: integer
      price:
        type: integer
      service_name:
        type: string
      start_date:
        $ref: '#/definitions/subscription-aggregator_pkg_month-year.MonthYear'
      updatedAt:
        type: string
      user_id:
        type: string
    type: object
  subscription-aggregator_pkg_month-year.MonthYear:
    properties:
      time.Time:
        type: string
    type: object
info:
  contact: {}
paths:
  /create:
    post:
      consumes:
      - application/json
      parameters:
      - description: Данные подписки
        in: body
        name: subscription
        required: true
        schema:
          $ref: '#/definitions/docs.SubscriptionExample'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/docs.MessageResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/docs.ErrorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/docs.ErrorResponse'
      summary: Создание подписки
  /delete/{id}:
    delete:
      parameters:
      - description: ID подписки
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/docs.MessageResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/docs.ErrorResponse'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/docs.ErrorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/docs.ErrorResponse'
      summary: Удалить подписку по ID
  /list:
    get:
      parameters:
      - description: ID пользователя
        in: query
        name: user_id
        type: string
      - description: Название сервиса
        in: query
        name: service_name
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/subscription-aggregator_internal_model.Subscription'
            type: array
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/docs.ErrorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/docs.ErrorResponse'
      summary: Получение списка подписок (есть фильтрация по ID пользователя и по
        названию сервиса)
  /read/{id}:
    get:
      parameters:
      - description: ID подписки
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/subscription-aggregator_internal_model.Subscription'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/docs.ErrorResponse'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/docs.ErrorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/docs.ErrorResponse'
      summary: Получить данные подписки по ID
  /sum:
    get:
      parameters:
      - description: ID пользователя
        in: query
        name: user_id
        required: true
        type: string
      - description: Название сервиса
        in: query
        name: service_name
        required: true
        type: string
      - default: 06-2025
        description: Начало периода в формате MM-YYYY
        in: query
        name: period_start
        required: true
        type: string
      - default: 08-2025
        description: Конец периода в формате MM-YYYY
        in: query
        name: period_end
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/docs.SumResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/docs.ErrorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/docs.ErrorResponse'
      summary: Получение суммы стоимости всех подписок за выбранный период по ID пользователя
        и имени сервиса
  /update/{id}:
    put:
      consumes:
      - application/json
      parameters:
      - description: ID подписки
        in: path
        name: id
        required: true
        type: integer
      - description: Новые данные подписки
        in: body
        name: subscription
        required: true
        schema:
          $ref: '#/definitions/docs.UpdateSubscriptionExample'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/docs.MessageResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/docs.ErrorResponse'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/docs.ErrorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/docs.ErrorResponse'
      summary: Обновить подписку по ID
swagger: "2.0"
