services:
  postgres:
    image: postgres:alpine
    environment:
      POSTGRES_DB: aggregator_db
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
    ports:
      - "5432:5432"
  subscription-aggregator:
    build: .
    depends_on:
      - postgres
    ports:
      - "8080:8080"