definitions:
  swagger.ErrorResponse400:
    properties:
      error:
        example: invalid {id/request/json}
        type: string
    type: object
  swagger.ErrorResponse404:
    properties:
      error:
        example: record not found in db
        type: string
    type: object
  swagger.ErrorResponse500:
    properties:
      error:
        example: failed to {create/find/update/delete} record in db
        type: string
    type: object
  swagger.MessageResponse:
    properties:
      id:
        example: 1
        type: integer
      message:
        example: '{created/updated/deleted}'
        type: string
    type: object
  swagger.SubscriptionExample:
    properties:
      price:
        example: 999
        type: integer
      service_name:
        example: Netflix
        type: string
      start_date:
        example: 07-2025
        type: string
      user_id:
        example: 11111111-1111-1111-1111-111111111111
        type: string
    type: object
  swagger.SubscriptionResponse:
    properties:
      id:
        example: 1
        type: integer
      price:
        example: 999
        type: integer
      service_name:
        example: Netflix
        type: string
      start_date:
        example: 07-2025
        type: string
      user_id:
        example: 11111111-1111-1111-1111-111111111111
        type: string
    type: object
  swagger.SumResponse:
    properties:
      sum_price:
        example: 999
        type: integer
    type: object
  swagger.UpdateSubscriptionExample:
    properties:
      price:
        example: 100
        type: integer
      service_name:
        example: Yandex
        type: string
    type: object
info:
  contact: {}
paths:
  /create:
    post:
      consumes:
      - application/json
      parameters:
      - description: Данные подписки
        in: body
        name: subscription
        required: true
        schema:
          $ref: '#/definitions/swagger.SubscriptionExample'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/swagger.MessageResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/swagger.ErrorResponse400'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/swagger.ErrorResponse500'
      summary: Создание подписки
  /delete/{id}:
    delete:
      parameters:
      - default: 1
        description: ID подписки
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/swagger.MessageResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/swagger.ErrorResponse400'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/swagger.ErrorResponse404'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/swagger.ErrorResponse500'
      summary: Удалить подписку по ID
  /list:
    get:
      parameters:
      - default: 11111111-1111-1111-1111-111111111111
        description: ID пользователя
        in: query
        name: user_id
        type: string
      - default: Netflix
        description: Название сервиса
        in: query
        name: service_name
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/swagger.SubscriptionResponse'
            type: array
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/swagger.ErrorResponse404'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/swagger.ErrorResponse500'
      summary: Получение списка подписок (есть фильтрация по ID пользователя и по
        названию сервиса)
  /read/{id}:
    get:
      parameters:
      - default: 1
        description: ID подписки
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/swagger.SubscriptionResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/swagger.ErrorResponse400'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/swagger.ErrorResponse404'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/swagger.ErrorResponse500'
      summary: Получить данные подписки по ID
  /sum:
    get:
      parameters:
      - default: 11111111-1111-1111-1111-111111111111
        description: ID пользователя
        in: query
        name: user_id
        required: true
        type: string
      - default: Netflix
        description: Название сервиса
        in: query
        name: service_name
        required: true
        type: string
      - default: 06-2025
        description: Начало периода в формате MM-YYYY
        in: query
        name: period_start
        required: true
        type: string
      - default: 08-2025
        description: Конец периода в формате MM-YYYY
        in: query
        name: period_end
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/swagger.SumResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/swagger.ErrorResponse400'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/swagger.ErrorResponse500'
      summary: Получение суммы стоимости всех подписок за выбранный период по ID пользователя
        и имени сервиса
  /update/{id}:
    put:
      consumes:
      - application/json
      parameters:
      - default: 1
        description: ID подписки
        in: path
        name: id
        required: true
        type: integer
      - description: Новые данные подписки
        in: body
        name: subscription
        required: true
        schema:
          $ref: '#/definitions/swagger.UpdateSubscriptionExample'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/swagger.MessageResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/swagger.ErrorResponse400'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/swagger.ErrorResponse404'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/swagger.ErrorResponse500'
      summary: Обновить подписку по ID
swagger: "2.0"
